const moreRecipes = [
  {
    id: 27,
    name: "Shahi Paneer",
    cuisine: "Indian",
    category: "Main Course",
    type: "Veg",
    time: "35 min",
    difficulty: "Medium",
    servings: 4,
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=900",
    ingredients: [
      "Paneer",
      "Onion",
      "Tomatoes",
      "Cashews",
      "Cream",
      "Butter",
      "Garam Masala",
      "Cardamom",
      "Salt",
    ],
    instructions: [
      "Cook onion and tomatoes until soft.",
      "Blend the mixture with cashews.",
      "Heat butter in a pan.",
      "Add the blended mixture and spices.",
      "Add cream and cook the gravy.",
      "Add paneer cubes.",
      "Simmer for 5 minutes.",
      "Serve hot with naan or rice.",
    ],
  },

  {
    id: 28,
    name: "Malai Kofta",
    cuisine: "Indian",
    category: "Main Course",
    type: "Veg",
    time: "50 min",
    difficulty: "Hard",
    servings: 4,
    image: "https://images.unsplash.com/photo-1631452180539-96aca7d48617?w=900",
    ingredients: [
      "Paneer",
      "Potatoes",
      "Corn Flour",
      "Cashews",
      "Cream",
      "Tomatoes",
      "Onion",
      "Garam Masala",
      "Salt",
    ],
    instructions: [
      "Mash paneer and potatoes together.",
      "Add corn flour and spices.",
      "Shape the mixture into small balls.",
      "Deep fry the koftas until golden.",
      "Prepare onion and tomato gravy.",
      "Blend the gravy until smooth.",
      "Add cream and koftas.",
      "Simmer and serve hot.",
    ],
  },

  {
    id: 29,
    name: "Rajma Masala",
    cuisine: "Indian",
    category: "Main Course",
    type: "Veg",
    time: "45 min",
    difficulty: "Easy",
    servings: 4,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=900",
    ingredients: [
      "Rajma",
      "Onion",
      "Tomatoes",
      "Ginger Garlic Paste",
      "Cumin",
      "Turmeric",
      "Garam Masala",
      "Red Chilli Powder",
      "Salt",
    ],
    instructions: [
      "Soak rajma overnight.",
      "Pressure cook rajma until soft.",
      "Heat oil and add cumin.",
      "Add onion and cook until golden.",
      "Add ginger garlic paste and tomatoes.",
      "Add spices and cook the masala.",
      "Add boiled rajma.",
      "Simmer for 10 minutes and serve.",
    ],
  },

  {
    id: 30,
    name: "Mix Veg Curry",
    cuisine: "Indian",
    category: "Main Course",
    type: "Veg",
    time: "35 min",
    difficulty: "Easy",
    servings: 4,
    image: "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?w=900",
    ingredients: [
      "Carrot",
      "Beans",
      "Peas",
      "Potato",
      "Capsicum",
      "Tomatoes",
      "Onion",
      "Garam Masala",
      "Salt",
    ],
    instructions: [
      "Chop all vegetables.",
      "Heat oil and cook onion.",
      "Add tomatoes and spices.",
      "Add chopped vegetables.",
      "Mix everything well.",
      "Add water and cover the pan.",
      "Cook until vegetables are tender.",
      "Serve hot with roti.",
    ],
  },

  {
    id: 31,
    name: "Matar Paneer",
    cuisine: "Indian",
    category: "Main Course",
    type: "Veg",
    time: "35 min",
    difficulty: "Medium",
    servings: 4,
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=900",
    ingredients: [
      "Paneer",
      "Green Peas",
      "Tomatoes",
      "Onion",
      "Ginger Garlic Paste",
      "Garam Masala",
      "Turmeric",
      "Cream",
      "Salt",
    ],
    instructions: [
      "Cook onion until golden.",
      "Add ginger garlic paste.",
      "Add tomatoes and spices.",
      "Cook until the masala becomes soft.",
      "Add green peas.",
      "Add paneer cubes.",
      "Add a little water and simmer.",
      "Finish with cream and serve.",
    ],
  },

  {
    id: 32,
    name: "Aloo Gobi",
    cuisine: "Indian",
    category: "Main Course",
    type: "Veg",
    time: "30 min",
    difficulty: "Easy",
    servings: 4,
    image: "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?w=900",
    ingredients: [
      "Potatoes",
      "Cauliflower",
      "Onion",
      "Tomato",
      "Turmeric",
      "Cumin",
      "Coriander Powder",
      "Red Chilli Powder",
      "Salt",
    ],
    instructions: [
      "Cut potatoes and cauliflower into pieces.",
      "Heat oil and add cumin.",
      "Add potatoes and cauliflower.",
      "Add turmeric and other spices.",
      "Add chopped onion and tomato.",
      "Cover and cook on low heat.",
      "Cook until vegetables become tender.",
      "Garnish with coriander.",
    ],
  },

  {
    id: 33,
    name: "Bhindi Masala",
    cuisine: "Indian",
    category: "Main Course",
    type: "Veg",
    time: "25 min",
    difficulty: "Easy",
    servings: 3,
    image: "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?w=900",
    ingredients: [
      "Okra",
      "Onion",
      "Tomatoes",
      "Cumin",
      "Turmeric",
      "Coriander Powder",
      "Red Chilli Powder",
      "Oil",
      "Salt",
    ],
    instructions: [
      "Wash and dry the okra.",
      "Cut okra into small pieces.",
      "Heat oil and sauté okra.",
      "Remove okra from the pan.",
      "Cook onion and tomatoes.",
      "Add spices.",
      "Add cooked okra.",
      "Mix well and serve.",
    ],
  },

  {
    id: 34,
    name: "Jeera Rice",
    cuisine: "Indian",
    category: "Rice",
    type: "Veg",
    time: "20 min",
    difficulty: "Easy",
    servings: 4,
    image: "https://images.unsplash.com/photo-1599043513900-ed6fe01d3833?w=900",
    ingredients: [
      "Basmati Rice",
      "Cumin Seeds",
      "Butter",
      "Green Chilli",
      "Bay Leaf",
      "Cinnamon",
      "Water",
      "Salt",
    ],
    instructions: [
      "Wash and soak basmati rice.",
      "Heat butter in a pan.",
      "Add cumin and whole spices.",
      "Add soaked rice.",
      "Add water and salt.",
      "Cover and cook until rice is tender.",
      "Fluff the rice gently.",
      "Serve hot.",
    ],
  },

  {
    id: 35,
    name: "Veg Pulao",
    cuisine: "Indian",
    category: "Rice",
    type: "Veg",
    time: "30 min",
    difficulty: "Easy",
    servings: 4,
    image: "https://images.unsplash.com/photo-1599043513900-ed6fe01d3833?w=900",
    ingredients: [
      "Basmati Rice",
      "Carrot",
      "Beans",
      "Peas",
      "Onion",
      "Green Chilli",
      "Whole Spices",
      "Ghee",
      "Salt",
    ],
    instructions: [
      "Wash and soak rice.",
      "Heat ghee and add whole spices.",
      "Add onion and green chilli.",
      "Add chopped vegetables.",
      "Add soaked rice.",
      "Add water and salt.",
      "Cover and cook until rice is done.",
      "Serve hot with raita.",
    ],
  },

  {
    id: 36,
    name: "Idli Sambar",
    cuisine: "Indian",
    category: "South Indian",
    type: "Veg",
    time: "40 min",
    difficulty: "Medium",
    servings: 4,
    image: "https://images.unsplash.com/photo-1630383249896-424e482df921?w=900",
    ingredients: [
      "Idli Batter",
      "Toor Dal",
      "Tomato",
      "Onion",
      "Carrot",
      "Sambar Masala",
      "Mustard Seeds",
      "Curry Leaves",
      "Salt",
    ],
    instructions: [
      "Prepare idli batter.",
      "Steam the batter in idli molds.",
      "Cook toor dal until soft.",
      "Add vegetables and sambar masala.",
      "Prepare tempering with mustard seeds.",
      "Add tempering to the sambar.",
      "Cook until vegetables are tender.",
      "Serve idli with hot sambar.",
    ],
  },

  {
    id: 37,
    name: "Medu Vada",
    cuisine: "Indian",
    category: "South Indian",
    type: "Veg",
    time: "40 min",
    difficulty: "Medium",
    servings: 4,
    image: "https://images.unsplash.com/photo-1630383249896-424e482df921?w=900",
    ingredients: [
      "Urad Dal",
      "Green Chilli",
      "Ginger",
      "Curry Leaves",
      "Black Pepper",
      "Salt",
      "Oil",
      "Water",
    ],
    instructions: [
      "Soak urad dal for several hours.",
      "Grind dal into a thick batter.",
      "Add chilli, ginger and spices.",
      "Shape batter into vadas.",
      "Heat oil in a deep pan.",
      "Deep fry until golden.",
      "Drain excess oil.",
      "Serve with sambar and chutney.",
    ],
  },

  {
    id: 38,
    name: "Poha",
    cuisine: "Indian",
    category: "Breakfast",
    type: "Veg",
    time: "20 min",
    difficulty: "Easy",
    servings: 3,
    image: "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?w=900",
    ingredients: [
      "Poha",
      "Onion",
      "Potato",
      "Peanuts",
      "Green Chilli",
      "Mustard Seeds",
      "Turmeric",
      "Coriander",
      "Salt",
    ],
    instructions: [
      "Wash poha gently.",
      "Heat oil and add mustard seeds.",
      "Add peanuts and green chilli.",
      "Add onion and potato.",
      "Cook until potato becomes soft.",
      "Add turmeric and salt.",
      "Add washed poha.",
      "Mix and garnish with coriander.",
    ],
  },

  {
    id: 39,
    name: "Dhokla",
    cuisine: "Indian",
    category: "Snack",
    type: "Veg",
    time: "35 min",
    difficulty: "Medium",
    servings: 6,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=900",
    ingredients: [
      "Gram Flour",
      "Yogurt",
      "Lemon Juice",
      "Eno",
      "Mustard Seeds",
      "Green Chilli",
      "Curry Leaves",
      "Sugar",
      "Salt",
    ],
    instructions: [
      "Mix gram flour with yogurt.",
      "Add water and prepare a smooth batter.",
      "Add lemon juice and seasoning.",
      "Add eno just before steaming.",
      "Pour batter into a greased tray.",
      "Steam until completely cooked.",
      "Prepare mustard seed tempering.",
      "Pour tempering over dhokla and serve.",
    ],
  },

  {
    id: 40,
    name: "Veg Manchurian",
    cuisine: "Indo-Chinese",
    category: "Starter",
    type: "Veg",
    time: "40 min",
    difficulty: "Medium",
    servings: 4,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=900",
    ingredients: [
      "Cabbage",
      "Carrot",
      "Capsicum",
      "Corn Flour",
      "Soy Sauce",
      "Chilli Sauce",
      "Garlic",
      "Spring Onion",
      "Salt",
    ],
    instructions: [
      "Chop all vegetables finely.",
      "Mix vegetables with corn flour.",
      "Shape the mixture into balls.",
      "Deep fry until golden.",
      "Prepare sauce with garlic and vegetables.",
      "Add soy sauce and chilli sauce.",
      "Add fried Manchurian balls.",
      "Garnish with spring onion.",
    ],
  },

  {
    id: 41,
    name: "Hakka Noodles",
    cuisine: "Indo-Chinese",
    category: "Noodles",
    type: "Veg",
    time: "25 min",
    difficulty: "Easy",
    servings: 3,
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=900",
    ingredients: [
      "Noodles",
      "Cabbage",
      "Carrot",
      "Capsicum",
      "Soy Sauce",
      "Vinegar",
      "Garlic",
      "Spring Onion",
      "Salt",
    ],
    instructions: [
      "Boil noodles until just cooked.",
      "Drain and rinse noodles.",
      "Heat oil in a wok.",
      "Add garlic and vegetables.",
      "Stir fry on high heat.",
      "Add soy sauce and vinegar.",
      "Add noodles and toss well.",
      "Garnish with spring onion.",
    ],
  },

  {
    id: 42,
    name: "White Sauce Pasta",
    cuisine: "Italian",
    category: "Pasta",
    type: "Veg",
    time: "30 min",
    difficulty: "Easy",
    servings: 3,
    image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=900",
    ingredients: [
      "Pasta",
      "Milk",
      "Butter",
      "Flour",
      "Cheese",
      "Capsicum",
      "Corn",
      "Black Pepper",
      "Salt",
    ],
    instructions: [
      "Boil pasta until al dente.",
      "Melt butter in a pan.",
      "Add flour and cook briefly.",
      "Gradually add milk.",
      "Stir until the sauce becomes creamy.",
      "Add cheese and vegetables.",
      "Add cooked pasta.",
      "Season and serve hot.",
    ],
  },

  {
    id: 43,
    name: "Arrabbiata Pasta",
    cuisine: "Italian",
    category: "Pasta",
    type: "Veg",
    time: "25 min",
    difficulty: "Easy",
    servings: 2,
    image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=900",
    ingredients: [
      "Pasta",
      "Tomatoes",
      "Garlic",
      "Red Chilli Flakes",
      "Olive Oil",
      "Basil",
      "Parmesan",
      "Salt",
    ],
    instructions: [
      "Boil pasta until al dente.",
      "Heat olive oil in a pan.",
      "Add garlic and chilli flakes.",
      "Add chopped tomatoes.",
      "Cook until sauce thickens.",
      "Add cooked pasta.",
      "Mix well with the sauce.",
      "Top with basil and parmesan.",
    ],
  },

  {
    id: 44,
    name: "Four Cheese Pizza",
    cuisine: "Italian",
    category: "Pizza",
    type: "Veg",
    time: "40 min",
    difficulty: "Medium",
    servings: 2,
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=900",
    ingredients: [
      "Pizza Dough",
      "Mozzarella",
      "Parmesan",
      "Cheddar",
      "Gorgonzola",
      "Tomato Sauce",
      "Olive Oil",
      "Basil",
    ],
    instructions: [
      "Roll out the pizza dough.",
      "Spread tomato sauce over the base.",
      "Add all four cheeses.",
      "Drizzle olive oil.",
      "Bake until cheese melts.",
      "Bake until the crust becomes golden.",
      "Add fresh basil.",
      "Serve hot.",
    ],
  },

  {
    id: 45,
    name: "Marinara Pasta",
    cuisine: "Italian",
    category: "Pasta",
    type: "Veg",
    time: "25 min",
    difficulty: "Easy",
    servings: 2,
    image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=900",
    ingredients: [
      "Pasta",
      "Tomatoes",
      "Garlic",
      "Onion",
      "Olive Oil",
      "Basil",
      "Oregano",
      "Salt",
    ],
    instructions: [
      "Cook pasta until al dente.",
      "Heat olive oil in a pan.",
      "Add garlic and onion.",
      "Add tomatoes and herbs.",
      "Cook until the sauce thickens.",
      "Add cooked pasta.",
      "Mix everything together.",
      "Garnish with basil and serve.",
    ],
  },

  {
    id: 46,
    name: "Caprese Salad",
    cuisine: "Italian",
    category: "Salad",
    type: "Veg",
    time: "10 min",
    difficulty: "Easy",
    servings: 2,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=900",
    ingredients: [
      "Tomatoes",
      "Mozzarella",
      "Fresh Basil",
      "Olive Oil",
      "Black Pepper",
      "Salt",
    ],
    instructions: [
      "Slice tomatoes and mozzarella.",
      "Arrange them on a plate.",
      "Add fresh basil leaves.",
      "Drizzle olive oil.",
      "Season with salt and pepper.",
      "Serve immediately.",
    ],
  },

  {
    id: 47,
    name: "Korean Vegetable Fried Rice",
    cuisine: "Korean",
    category: "Rice",
    type: "Veg",
    time: "25 min",
    difficulty: "Easy",
    servings: 3,
    image: "https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=900",
    ingredients: [
      "Rice",
      "Carrot",
      "Peas",
      "Corn",
      "Spring Onion",
      "Soy Sauce",
      "Sesame Oil",
      "Garlic",
      "Sesame Seeds",
    ],
    instructions: [
      "Cook rice and let it cool.",
      "Heat sesame oil in a pan.",
      "Add garlic and vegetables.",
      "Stir fry until vegetables are tender.",
      "Add cooked rice.",
      "Add soy sauce and mix well.",
      "Cook for a few minutes.",
      "Garnish with sesame seeds.",
    ],
  },

  {
    id: 48,
    name: "Korean Vegetable Pancake",
    cuisine: "Korean",
    category: "Starter",
    type: "Veg",
    time: "25 min",
    difficulty: "Easy",
    servings: 3,
    image: "https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=900",
    ingredients: [
      "Flour",
      "Carrot",
      "Spring Onion",
      "Cabbage",
      "Water",
      "Soy Sauce",
      "Sesame Oil",
      "Salt",
    ],
    instructions: [
      "Prepare a smooth flour batter.",
      "Add chopped vegetables.",
      "Mix vegetables into the batter.",
      "Heat oil in a pan.",
      "Pour the batter into the pan.",
      "Cook until the bottom becomes crispy.",
      "Flip and cook the other side.",
      "Serve with soy dipping sauce.",
    ],
  },

  {
    id: 49,
    name: "Korean Cucumber Salad",
    cuisine: "Korean",
    category: "Salad",
    type: "Veg",
    time: "10 min",
    difficulty: "Easy",
    servings: 2,
    image: "https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=900",
    ingredients: [
      "Cucumber",
      "Gochugaru",
      "Sesame Oil",
      "Rice Vinegar",
      "Garlic",
      "Sesame Seeds",
      "Spring Onion",
      "Salt",
    ],
    instructions: [
      "Slice cucumbers thinly.",
      "Add salt and let them rest briefly.",
      "Mix gochugaru with sesame oil.",
      "Add vinegar and garlic.",
      "Add cucumber slices.",
      "Toss everything together.",
      "Garnish with sesame seeds.",
      "Serve chilled.",
    ],
  },

  {
    id: 50,
    name: "Korean Vegetable Soup",
    cuisine: "Korean",
    category: "Soup",
    type: "Veg",
    time: "30 min",
    difficulty: "Easy",
    servings: 4,
    image: "https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=900",
    ingredients: [
      "Cabbage",
      "Carrot",
      "Mushrooms",
      "Spring Onion",
      "Garlic",
      "Soy Sauce",
      "Sesame Oil",
      "Vegetable Stock",
    ],
    instructions: [
      "Heat sesame oil in a pot.",
      "Add garlic and vegetables.",
      "Stir fry for a few minutes.",
      "Add vegetable stock.",
      "Add soy sauce.",
      "Bring the soup to a boil.",
      "Simmer until vegetables are tender.",
      "Garnish with spring onion.",
    ],
  },

  {
    id: 51,
    name: "Mango Lassi",
    cuisine: "Indian",
    category: "Drinks",
    type: "Veg",
    time: "10 min",
    difficulty: "Easy",
    servings: 2,
    image: "https://images.unsplash.com/photo-1546173159-315724a31696?w=900",
    ingredients: [
      "Mango",
      "Yogurt",
      "Milk",
      "Sugar",
      "Cardamom",
      "Ice",
    ],
    instructions: [
      "Peel and chop mangoes.",
      "Add mangoes to a blender.",
      "Add yogurt and milk.",
      "Add sugar and cardamom.",
      "Blend until smooth.",
      "Add ice if desired.",
      "Blend again briefly.",
      "Serve chilled.",
    ],
  },

  {
    id: 52,
    name: "Masala Chai",
    cuisine: "Indian",
    category: "Drinks",
    type: "Veg",
    time: "15 min",
    difficulty: "Easy",
    servings: 2,
    image: "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?w=900",
    ingredients: [
      "Tea Leaves",
      "Milk",
      "Water",
      "Ginger",
      "Cardamom",
      "Cinnamon",
      "Sugar",
    ],
    instructions: [
      "Boil water in a saucepan.",
      "Add ginger and whole spices.",
      "Add tea leaves.",
      "Boil for a few minutes.",
      "Add milk and sugar.",
      "Simmer until fragrant.",
      "Strain the tea.",
      "Serve hot.",
    ],
  },

  {
    id: 53,
    name: "Jalebi",
    cuisine: "Indian",
    category: "Sweets",
    type: "Veg",
    time: "45 min",
    difficulty: "Medium",
    servings: 6,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=900",
    ingredients: [
      "Flour",
      "Corn Flour",
      "Yogurt",
      "Sugar",
      "Water",
      "Saffron",
      "Cardamom",
      "Oil",
    ],
    instructions: [
      "Prepare a smooth jalebi batter.",
      "Let the batter rest.",
      "Prepare sugar syrup.",
      "Heat oil in a pan.",
      "Pipe batter into spiral shapes.",
      "Fry until crisp and golden.",
      "Soak jalebi in sugar syrup.",
      "Serve warm.",
    ],
  },

  {
    id: 54,
    name: "Rasgulla",
    cuisine: "Indian",
    category: "Sweets",
    type: "Veg",
    time: "50 min",
    difficulty: "Medium",
    servings: 6,
    image: "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?w=900",
    ingredients: [
      "Milk",
      "Lemon Juice",
      "Sugar",
      "Water",
      "Cardamom",
      "Rose Water",
    ],
    instructions: [
      "Boil the milk.",
      "Add lemon juice to curdle the milk.",
      "Strain and wash the paneer.",
      "Knead the paneer until smooth.",
      "Shape into small balls.",
      "Prepare sugar syrup.",
      "Cook the balls in the syrup.",
      "Add rose water and serve chilled.",
    ],
  },

  {
    id: 55,
    name: "Besan Ladoo",
    cuisine: "Indian",
    category: "Sweets",
    type: "Veg",
    time: "35 min",
    difficulty: "Easy",
    servings: 8,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=900",
    ingredients: [
      "Gram Flour",
      "Ghee",
      "Sugar",
      "Cardamom",
      "Almonds",
      "Cashews",
    ],
    instructions: [
      "Heat ghee in a pan.",
      "Add gram flour.",
      "Roast slowly until fragrant.",
      "Allow the mixture to cool slightly.",
      "Add powdered sugar and cardamom.",
      "Mix everything well.",
      "Shape the mixture into small balls.",
      "Garnish with chopped nuts.",
    ],
  },

  {
    id: 56,
    name: "Chocolate Brownie",
    cuisine: "International",
    category: "Dessert",
    type: "Veg",
    time: "40 min",
    difficulty: "Medium",
    servings: 8,
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=900",
    ingredients: [
      "Flour",
      "Cocoa Powder",
      "Sugar",
      "Butter",
      "Milk",
      "Chocolate",
      "Vanilla",
      "Baking Powder",
    ],
    instructions: [
      "Melt butter and chocolate together.",
      "Add sugar and vanilla.",
      "Mix flour and cocoa powder separately.",
      "Combine dry and wet ingredients.",
      "Add milk and mix gently.",
      "Pour batter into a baking tray.",
      "Bake until set.",
      "Cool and cut into squares.",
    ],
  },

  {
    id: 57,
    name: "Chocolate Cake",
    cuisine: "International",
    category: "Dessert",
    type: "Veg",
    time: "50 min",
    difficulty: "Medium",
    servings: 8,
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=900",
    ingredients: [
      "Flour",
      "Cocoa Powder",
      "Sugar",
      "Milk",
      "Butter",
      "Baking Powder",
      "Vanilla",
      "Chocolate Frosting",
    ],
    instructions: [
      "Mix flour and cocoa powder.",
      "Add sugar and baking powder.",
      "Add milk, butter and vanilla.",
      "Prepare a smooth batter.",
      "Pour batter into a cake pan.",
      "Bake until completely cooked.",
      "Cool the cake.",
      "Cover with chocolate frosting.",
    ],
  },

  {
    id: 58,
    name: "Strawberry Cheesecake",
    cuisine: "International",
    category: "Dessert",
    type: "Veg",
    time: "60 min",
    difficulty: "Hard",
    servings: 8,
    image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=900",
    ingredients: [
      "Cream Cheese",
      "Biscuits",
      "Butter",
      "Sugar",
      "Cream",
      "Strawberries",
      "Vanilla",
      "Gelatin",
    ],
    instructions: [
      "Crush biscuits into fine crumbs.",
      "Mix crumbs with melted butter.",
      "Press the mixture into a cake tin.",
      "Beat cream cheese with sugar.",
      "Add cream and vanilla.",
      "Add prepared gelatin.",
      "Pour mixture over the biscuit base.",
      "Chill and decorate with strawberries.",
    ],
  },

  {
    id: 59,
    name: "Apple Pie",
    cuisine: "International",
    category: "Dessert",
    type: "Veg",
    time: "60 min",
    difficulty: "Medium",
    servings: 8,
    image: "https://images.unsplash.com/photo-1535920527002-b35e96722e09?w=900",
    ingredients: [
      "Apples",
      "Flour",
      "Butter",
      "Sugar",
      "Cinnamon",
      "Nutmeg",
      "Lemon Juice",
      "Water",
    ],
    instructions: [
      "Prepare the pie dough.",
      "Peel and slice apples.",
      "Mix apples with sugar and spices.",
      "Place the apple mixture into the crust.",
      "Cover with another layer of dough.",
      "Seal the edges.",
      "Bake until golden brown.",
      "Cool slightly before serving.",
    ],
  },

  {
    id: 60,
    name: "Chocolate Mousse",
    cuisine: "International",
    category: "Dessert",
    type: "Veg",
    time: "25 min",
    difficulty: "Easy",
    servings: 4,
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=900",
    ingredients: [
      "Dark Chocolate",
      "Cream",
      "Sugar",
      "Vanilla",
      "Cocoa Powder",
    ],
    instructions: [
      "Melt the chocolate gently.",
      "Whip the cream until fluffy.",
      "Add sugar and vanilla.",
      "Fold melted chocolate into the cream.",
      "Mix gently until smooth.",
      "Pour into serving glasses.",
      "Refrigerate until set.",
      "Dust with cocoa powder and serve.",
    ],
  },
];

export default moreRecipes;
