 export const beverageData = [
  {
    id: 1,
    name: "Classic Cold Coffee",
    price: 129,
    rating: 4.8,
    stars: "★★★★★",
    time: "7 min",
    category: "Coffee",
    image: "/images/beverages/classic-cold-coffee.jpg",
  },
  {
    id: 2,
    name: "Chocolate Cold Coffee",
    price: 149,
    rating: 4.9,
    stars: "★★★★★",
    time: "8 min",
    category: "Coffee",
    image: "/images/beverages/chocolate-cold-coffee.jpg",
  },
  {
    id: 3,
    name: "Hazelnut Coffee",
    price: 169,
    rating: 4.8,
    stars: "★★★★★",
    time: "8 min",
    category: "Coffee",
    image: "/images/beverages/hazelnut-coffee.jpg",
  },
  {
    id: 4,
    name: "Caramel Coffee",
    price: 159,
    rating: 4.7,
    stars: "★★★★★",
    time: "8 min",
    category: "Coffee",
    image: "/images/beverages/caramel-coffee.jpg",
  },
  {
    id: 5,
    name: "Vanilla Iced Coffee",
    price: 149,
    rating: 4.7,
    stars: "★★★★★",
    time: "7 min",
    category: "Coffee",
    image: "/images/beverages/vanilla-iced-coffee.jpg",
  },
  {
    id: 6,
    name: "Mocha Frappe",
    price: 179,
    rating: 4.9,
    stars: "★★★★★",
    time: "9 min",
    category: "Coffee",
    image: "/images/beverages/mocha-frappe.jpg",
  },
  {
    id: 7,
    name: "Cappuccino",
    price: 139,
    rating: 4.8,
    stars: "★★★★★",
    time: "6 min",
    category: "Coffee",
    image: "/images/beverages/cappuccino.jpg",
  },
  {
    id: 8,
    name: "Iced Latte",
    price: 149,
    rating: 4.7,
    stars: "★★★★★",
    time: "7 min",
    category: "Coffee",
    image: "/images/beverages/iced-latte.jpg",
  },

  {
    id: 9,
    name: "Mango Shake",
    price: 139,
    rating: 4.9,
    stars: "★★★★★",
    time: "7 min",
    category: "Shake",
    image: "/images/beverages/mango-shake.jpg",
  },
  {
    id: 10,
    name: "Strawberry Shake",
    price: 149,
    rating: 4.8,
    stars: "★★★★★",
    time: "7 min",
    category: "Shake",
    image: "/images/beverages/strawberry-shake.jpg",
  },
  {
    id: 11,
    name: "Chocolate Shake",
    price: 159,
    rating: 4.9,
    stars: "★★★★★",
    time: "8 min",
    category: "Shake",
    image: "/images/beverages/chocolate-shake.jpg",
  },
  {
    id: 12,
    name: "Oreo Shake",
    price: 169,
    rating: 4.9,
    stars: "★★★★★",
    time: "8 min",
    category: "Shake",
    image: "/images/beverages/oreo-shake.jpg",
  },
  {
    id: 13,
    name: "Vanilla Shake",
    price: 139,
    rating: 4.7,
    stars: "★★★★★",
    time: "7 min",
    category: "Shake",
    image: "/images/beverages/vanilla-shake.jpg",
  },
  {
    id: 14,
    name: "Butterscotch Shake",
    price: 159,
    rating: 4.8,
    stars: "★★★★★",
    time: "8 min",
    category: "Shake",
    image: "/images/beverages/butterscotch-shake.jpg",
  },
  {
    id: 15,
    name: "KitKat Shake",
    price: 179,
    rating: 4.9,
    stars: "★★★★★",
    time: "9 min",
    category: "Shake",
    image: "/images/beverages/kitkat-shake.jpg",
  },
  {
    id: 16,
    name: "Brownie Shake",
    price: 189,
    rating: 4.8,
    stars: "★★★★★",
    time: "9 min",
    category: "Shake",
    image: "/images/beverages/brownie-shake.jpg",
  },

  {
    id: 17,
    name: "Fresh Mango Juice",
    price: 119,
    rating: 4.8,
    stars: "★★★★★",
    time: "6 min",
    category: "Juice",
    image: "/images/beverages/fresh-mango-juice.jpg",
  },
  {
    id: 18,
    name: "Fresh Orange Juice",
    price: 109,
    rating: 4.7,
    stars: "★★★★★",
    time: "5 min",
    category: "Juice",
    image: "/images/beverages/fresh-orange-juice.jpg",
  },
  {
    id: 19,
    name: "Pineapple Juice",
    price: 119,
    rating: 4.6,
    stars: "★★★★★",
    time: "6 min",
    category: "Juice",
    image: "/images/beverages/pineapple-juice.jpg",
  },
  {
    id: 20,
    name: "Watermelon Juice",
    price: 99,
    rating: 4.7,
    stars: "★★★★★",
    time: "5 min",
    category: "Juice",
    image: "/images/beverages/watermelon-juice.jpg",
  },
  {
    id: 21,
    name: "Pomegranate Juice",
    price: 149,
    rating: 4.8,
    stars: "★★★★★",
    time: "6 min",
    category: "Juice",
    image: "/images/beverages/pomegranate-juice.jpg",
  },
  {
    id: 22,
    name: "Apple Juice",
    price: 119,
    rating: 4.6,
    stars: "★★★★★",
    time: "5 min",
    category: "Juice",
    image: "/images/beverages/apple-juice.jpg",
  },
  {
    id: 23,
    name: "Mixed Fruit Juice",
    price: 139,
    rating: 4.8,
    stars: "★★★★★",
    time: "7 min",
    category: "Juice",
    image: "/images/beverages/mixed-fruit-juice.jpg",
  },
  {
    id: 24,
    name: "Kiwi Juice",
    price: 159,
    rating: 4.7,
    stars: "★★★★★",
    time: "7 min",
    category: "Juice",
    image: "/images/beverages/kiwi-juice.jpg",
  },

  {
    id: 25,
    name: "Mango Smoothie",
    price: 149,
    rating: 4.9,
    stars: "★★★★★",
    time: "7 min",
    category: "Smoothie",
    image: "/images/beverages/mango-smoothie.jpg",
  },
  {
    id: 26,
    name: "Strawberry Smoothie",
    price: 159,
    rating: 4.8,
    stars: "★★★★★",
    time: "7 min",
    category: "Smoothie",
    image: "/images/beverages/strawberry-smoothie.jpg",
  },
  {
    id: 27,
    name: "Blueberry Smoothie",
    price: 179,
    rating: 4.9,
    stars: "★★★★★",
    time: "8 min",
    category: "Smoothie",
    image: "/images/beverages/blueberry-smoothie.jpg",
  },
  {
    id: 28,
    name: "Banana Smoothie",
    price: 129,
    rating: 4.7,
    stars: "★★★★★",
    time: "6 min",
    category: "Smoothie",
    image: "/images/beverages/banana-smoothie.jpg",
  },
  {
    id: 29,
    name: "Pineapple Smoothie",
    price: 149,
    rating: 4.7,
    stars: "★★★★★",
    time: "7 min",
    category: "Smoothie",
    image: "/images/beverages/pineapple-smoothie.jpg",
  },
  {
    id: 30,
    name: "Green Detox Smoothie",
    price: 179,
    rating: 4.6,
    stars: "★★★★★",
    time: "8 min",
    category: "Smoothie",
    image: "/images/beverages/green-detox-smoothie.jpg",
  },

  {
    id: 31,
    name: "Classic Lemonade",
    price: 89,
    rating: 4.7,
    stars: "★★★★★",
    time: "5 min",
    category: "Cooler",
    image: "/images/beverages/classic-lemonade.jpg",
  },
  {
    id: 32,
    name: "Mint Lemonade",
    price: 99,
    rating: 4.8,
    stars: "★★★★★",
    time: "5 min",
    category: "Cooler",
    image: "/images/beverages/mint-lemonade.jpg",
  },
  {
    id: 33,
    name: "Strawberry Lemonade",
    price: 119,
    rating: 4.8,
    stars: "★★★★★",
    time: "6 min",
    category: "Cooler",
    image: "/images/beverages/strawberry-lemonade.jpg",
  },
  {
    id: 34,
    name: "Blue Lagoon Cooler",
    price: 129,
    rating: 4.7,
    stars: "★★★★★",
    time: "6 min",
    category: "Cooler",
    image: "/images/beverages/blue-lagoon-cooler.jpg",
  },
  {
    id: 35,
    name: "Green Apple Cooler",
    price: 129,
    rating: 4.8,
    stars: "★★★★★",
    time: "6 min",
    category: "Cooler",
    image: "/images/beverages/green-apple-cooler.jpg",
  },
  {
    id: 36,
    name: "Peach Iced Tea",
    price: 119,
    rating: 4.7,
    stars: "★★★★★",
    time: "6 min",
    category: "Cooler",
    image: "/images/beverages/peach-iced-tea.jpg",
  },

  {
    id: 37,
    name: "Masala Chai",
    price: 69,
    rating: 4.8,
    stars: "★★★★★",
    time: "5 min",
    category: "Tea",
    image: "/images/beverages/masala-chai.jpg",
  },
  {
    id: 38,
    name: "Ginger Tea",
    price: 69,
    rating: 4.7,
    stars: "★★★★★",
    time: "5 min",
    category: "Tea",
    image: "/images/beverages/ginger-tea.jpg",
  },
  {
    id: 39,
    name: "Lemon Tea",
    price: 79,
    rating: 4.6,
    stars: "★★★★★",
    time: "5 min",
    category: "Tea",
    image: "/images/beverages/lemon-tea.jpg",
  },
  {
    id: 40,
    name: "Green Tea",
    price: 89,
    rating: 4.7,
    stars: "★★★★★",
    time: "5 min",
    category: "Tea",
    image: "/images/beverages/green-tea.jpg",
  },
  {
    id: 41,
    name: "Peach Green Tea",
    price: 109,
    rating: 4.8,
    stars: "★★★★★",
    time: "6 min",
    category: "Tea",
    image: "/images/beverages/peach-green-tea.jpg",
  },
  {
    id: 42,
    name: "Iced Lemon Tea",
    price: 99,
    rating: 4.7,
    stars: "★★★★★",
    time: "5 min",
    category: "Tea",
    image: "/images/beverages/iced-lemon-tea.jpg",
  },

  {
    id: 43,
    name: "Vanilla Milkshake",
    price: 139,
    rating: 4.7,
    stars: "★★★★★",
    time: "7 min",
    category: "Milkshake",
    image: "/images/beverages/vanilla-milkshake.jpg",
  },
  {
    id: 44,
    name: "Chocolate Milkshake",
    price: 159,
    rating: 4.9,
    stars: "★★★★★",
    time: "8 min",
    category: "Milkshake",
    image: "/images/beverages/chocolate-milkshake.jpg",
  },
  {
    id: 45,
    name: "Strawberry Milkshake",
    price: 149,
    rating: 4.8,
    stars: "★★★★★",
    time: "7 min",
    category: "Milkshake",
    image: "/images/beverages/strawberry-milkshake.jpg",
  },
  {
    id: 46,
    name: "Mango Milkshake",
    price: 149,
    rating: 4.9,
    stars: "★★★★★",
    time: "7 min",
    category: "Milkshake",
    image: "/images/beverages/mango-milkshake.jpg",
  },
  {
    id: 47,
    name: "Pistachio Milkshake",
    price: 179,
    rating: 4.8,
    stars: "★★★★★",
    time: "8 min",
    category: "Milkshake",
    image: "/images/beverages/pistachio-milkshake.jpg",
  },
  {
    id: 48,
    name: "Coffee Milkshake",
    price: 169,
    rating: 4.8,
    stars: "★★★★★",
    time: "8 min",
    category: "Milkshake",
    image: "/images/beverages/coffee-milkshake.jpg",
  },

  {
    id: 49,
    name: "Virgin Mojito",
    price: 119,
    rating: 4.8,
    stars: "★★★★★",
    time: "6 min",
    category: "Mocktail",
    image: "/images/beverages/virgin-mojito.jpg",
  },
  {
    id: 50,
    name: "Strawberry Mojito",
    price: 139,
    rating: 4.9,
    stars: "★★★★★",
    time: "7 min",
    category: "Mocktail",
    image: "/images/beverages/strawberry-mojito.jpg",
  },
  {
    id: 51,
    name: "Blueberry Mojito",
    price: 149,
    rating: 4.8,
    stars: "★★★★★",
    time: "7 min",
    category: "Mocktail",
    image: "/images/beverages/blueberry-mojito.jpg",
  },
  {
    id: 52,
    name: "Watermelon Mojito",
    price: 129,
    rating: 4.7,
    stars: "★★★★★",
    time: "6 min",
    category: "Mocktail",
    image: "/images/beverages/watermelon-mojito.jpg",
  },

  {
    id: 53,
    name: "Classic Lassi",
    price: 89,
    rating: 4.8,
    stars: "★★★★★",
    time: "5 min",
    category: "Lassi",
    image: "/images/beverages/classic-lassi.jpg",
  },
  {
    id: 54,
    name: "Sweet Lassi",
    price: 99,
    rating: 4.9,
    stars: "★★★★★",
    time: "5 min",
    category: "Lassi",
    image: "/images/beverages/sweet-lassi.jpg",
  },
  {
    id: 55,
    name: "Mango Lassi",
    price: 119,
    rating: 4.9,
    stars: "★★★★★",
    time: "6 min",
    category: "Lassi",
    image: "/images/beverages/mango-lassi.jpg",
  },
  {
    id: 56,
    name: "Rose Lassi",
    price: 109,
    rating: 4.7,
    stars: "★★★★★",
    time: "5 min",
    category: "Lassi",
    image: "/images/beverages/rose-lassi.jpg",
  },

  {
    id: 57,
    name: "Fresh Lime Soda",
    price: 89,
    rating: 4.6,
    stars: "★★★★★",
    time: "5 min",
    category: "Soda",
    image: "/images/beverages/fresh-lime-soda.jpg",
  },
  {
    id: 58,
    name: "Mint Soda",
    price: 99,
    rating: 4.7,
    stars: "★★★★★",
    time: "5 min",
    category: "Soda",
    image: "/images/beverages/mint-soda.jpg",
  },
  {
    id: 59,
    name: "Masala Soda",
    price: 89,
    rating: 4.5,
    stars: "★★★★☆",
    time: "5 min",
    category: "Soda",
    image: "/images/beverages/masala-soda.jpg",
  },
  {
    id: 60,
    name: "Cucumber Mint Cooler",
    price: 129,
    rating: 4.8,
    stars: "★★★★★",
    time: "6 min",
    category: "Cooler",
    image: "/images/beverages/cucumber-mint-cooler.jpg",
  },
];
